<?php

namespace DuncanMcClean\SimpleCommerce\Fieldtypes;

use Facades\Statamic\Fieldtypes\RowId;
use Statamic\Fields\Values;
use Statamic\Fieldtypes\Grid;

class LineItemsFieldtype extends Grid
{
    protected function configFieldItems(): array
    {
        return [];
    }

    public function component(): string
    {
        return 'grid'; // TODO: Change the autogenerated stub
    }

    public function augment($value)
    {
        return $this->performAugmentation($value, false);
    }

    public function shallowAugment($value)
    {
        return $this->performAugmentation($value, true);
    }

    /**
     * The code for this method is pretty much exactly the same as the original method in the Grid fieldtype.
     * Just we need to do some stuff to map the value and we can't extend the Grid fieldtype's implementation since the method is private.
     *
     * @param $value
     * @param $shallow
     * @return array
     */
    private function performAugmentation($value, $shallow)
    {
        $method = $shallow ? 'shallowAugment' : 'augment';

        $value = $value->map->toArray()->all();

        return collect($value)->map(function ($row, $index) use ($method) {
            $values = $this->fields($index)->addValues($row)->{$method}()->values();

            return new Values($values->merge([RowId::handle() => $row[RowId::handle()] ?? null])->all());
        })->all();
    }
}