name: Pull Request Title

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pr-title:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: deepakputhraya/action-pr-title@077bddd7bdabd0d2b1b25ed0754c7e62e184d7ee # master
        with:
          regex: '^\[\d+\.x\]\s'
