name: Pull Request Title

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pr-title:
    name: Validate PR title
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: Check PR title format
        uses: deepakputhraya/action-pr-title@3864bebc79c5f829d25dd42d3c6579d040b0ef16 # v1.0.2
        with:
          regex: '^\[\d+\.x\]\s'
